---
# golangci options
run:
  timeout: 3m
issues:
  exclude-dirs:
    - cmd/playground
output:
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false
  gci:
    custom-order: true
    sections:
      - standard
      - prefix(github.com/toggl/toggl_work_api)
      - default
  gocognit:
    min-complexity: 15
  govet:
    enable:
      - fieldalignment
  revive:
    ignore-generated-header: false
    severity: warning
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
#      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
linters:
  enable:
    # Enable by default, see more in https://golangci-lint.run/usage/linters/#enabled-by-default-linters
    - errcheck
    - gci
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Custom to project, see more in https://golangci-lint.run/usage/linters/#disabled-by-default-linters--e--enable
    # - gosec
    - godot
    # - gocognit
    # - gocyclo
    - gofmt
    - revive
    - gofumpt
    - asciicheck
    - dogsled
    - copyloopvar
    - errcheck
    - gocritic
    - goimports
    - goprintffuncname
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace


