name: Code Quality
on:
  pull_request:
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.56.2