name: Deploy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  deploy:
    name: hetzner-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Lichess Bot on Hetzner
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd tofiks
            git checkout .
            git checkout master
            git pull
            /usr/local/go/bin/go build -o tofiks cmd/tofiks/main.go
            systemctl stop tofiks
            cp tofiks ~/lichess-bot/engines/tofiks
            systemctl start tofiks
            exit